// Generated by Wrangler by running `wrangler types`

interface Env {
	TRANSCRIBER_KV: KVNamespace;
	SSO_BASE_URL: "https://wacs-dev.bibletranslationtools.org";
	SSO_CLIENT_ID: "c9812108-0bbb-4917-8e1d-b952598f1c83";
	SSO_REDIRECT_PATH: "/Transcriber";
	OPENAI_KEY: string;
	SSO_CLIENT_SECRET: string;
	ASSETS: Fetcher;
	HTR_STORAGE: R2Bucket;
	HTR_DATABASE: D1Database;
}
