export const WACS_API_TOKEN = "transcriber_api_token";
// export const WACS_API_REFRESH_TOKEN = "transcriber_refresh_token";
// export const WACS_USER_TOKEN = "transcriber_id_token";
export const GRANT_REFRESH_TOKEN = "refresh_token";
export const GRANT_CODE_FLOW = "authorization_code";
export const CACHED_JWKS_KEY = "cached_jwks";
export const R2_JWKS_SYNC_SECONDS = 60 * 5;
export const transcribeRoute = "/transcriber/";
export const updateTranscriptionRoute = "/updateTranscription/";
